name: Security Checks

on:
  pull_request:
    branches:
      - mc-master
  push:
    branches:
      - mc-master

permissions:
  contents: read

jobs:
  snyk-sast:
    name: Snyk Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # Please fix these issues!
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: "--severity-threshold=medium --org=current-cloud"
  
  snyk-sca:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Set up Node
          uses: actions/setup-node@v3
          with:
            node-version: '16'
  
        - name: Install Gulp
          run: npm install -g gulp-cli
  
        - name: Install other dependencies
          run: npm install -f

        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            args: --severity-threshold=high

        - name: Monitor the vulns in the Snyk Dashboard
          uses: snyk/actions/gradle-jdk17@master
          if: github.event_name == 'push'
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: monitor
            args: "--org=qx --target-reference=${{ github.head_ref || github.ref_name }} --project-tags=branch=${{ github.head_ref || github.ref_name }},network=external,repo=Github_${{ github.event.repository.name }}"
    